--
-- This file was generated on 11/04/2015 at 06:42:02 AM.
-- It contains HsqlDb version 1.8.0.8 compatible SQL statements.
--

INSERT INTO RT_WORKFLOW_COMMENT( WORKFLOW_ID, COMMENT_ID) VALUES( 101, 100);

INSERT INTO RT_WORKFLOW_COMMENT( WORKFLOW_ID, COMMENT_ID) VALUES( 101, 101);

INSERT INTO RT_WORKFLOW_COMMENT( WORKFLOW_ID, COMMENT_ID) VALUES( 101, 102);

INSERT INTO RT_WORKFLOW_COMMENT( WORKFLOW_ID, COMMENT_ID) VALUES( 101, 103);

INSERT INTO RT_WORKFLOW_COMMENT( WORKFLOW_ID, COMMENT_ID) VALUES( 101, 104);

INSERT INTO RT_WORKFLOW_COMMENT( WORKFLOW_ID, COMMENT_ID) VALUES( 101, 105);


COMMIT WORK;