--
-- This file was generated on 11/04/2015 at 06:40:41 AM.
-- It contains HsqlDb version 1.8.0.8 compatible SQL statements.
--

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 1, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 2, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 3, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 4, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 5, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 6, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 7, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 2);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 3);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 4);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 8, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 9, 1);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 9, 6);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 9, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 9, 8);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 10, 5);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 10, 7);

INSERT INTO RT_WORKFLOW_PHASE_AVAIL_STATUS( PHASE_ID, STATUS_ID) VALUES( 10, 8);


COMMIT WORK;