package com.fdc.boarding.core.datadef;

import java.util.HashMap;

import org.joda.time.DateTimeZone;

/**
 *
 */
public enum TimeZoneId
{
      America_Adak                  ( "America/Adak"                    , "America/Adak"                    )
    , America_Anchorage             ( "America/Anchorage"               , "America/Anchorage"               )
    , America_Anguilla              ( "America/Anguilla"                , "America/Anguilla"                )
    , America_Antigua               ( "America/Antigua"                 , "America/Antigua"                 )
    , America_Araguaina             ( "America/Araguaina"               , "America/Araguaina"               )
    , America_Aruba                 ( "America/Aruba"                   , "America/Aruba"                   )
    , America_Asuncion              ( "America/Asuncion"                , "America/Asuncion"                )
    , America_Atka                  ( "America/Atka"                    , "America/Atka"                    )
    , America_Bahia                 ( "America/Bahia"                   , "America/Bahia"                   )
    , America_Barbados              ( "America/Barbados"                , "America/Barbados"                )
    , America_Belem                 ( "America/Belem"                   , "America/Belem"                   )
    , America_Belize                ( "America/Belize"                  , "America/Belize"                  )
    , America_Boa_Vista             ( "America/Boa_Vista"               , "America/Boa Vista"               )
    , America_Bogota                ( "America/Bogota"                  , "America/Bogota"                  )
    , America_Boise                 ( "America/Boise"                   , "America/Boise"                   )
    , America_Buenos_Aires          ( "America/Buenos_Aires"            , "America/Buenos Aires"            )
    , America_Cambridge_Bay         ( "America/Cambridge_Bay"           , "America/Cambridge Bay"           )
    , America_Campo_Grande          ( "America/Campo_Grande"            , "America/Campo Grande"            )
    , America_Cancun                ( "America/Cancun"                  , "America/Cancun"                  )
    , America_Caracas               ( "America/Caracas"                 , "America/Caracas"                 )
    , America_Catamarca             ( "America/Catamarca"               , "America/Catamarca"               )
    , America_Cayenne               ( "America/Cayenne"                 , "America/Cayenne"                 )
    , America_Cayman                ( "America/Cayman"                  , "America/Cayman"                  )
    , America_Chicago               ( "America/Chicago"                 , "America/Chicago"                 )
    , America_Chihuahua             ( "America/Chihuahua"               , "America/Chihuahua"               )
    , America_Cordoba               ( "America/Cordoba"                 , "America/Cordoba"                 )
    , America_Costa_Rica            ( "America/Costa_Rica"              , "America/Costa Rica"              )
    , America_Cuiaba                ( "America/Cuiaba"                  , "America/Cuiaba"                  )
    , America_Curacao               ( "America/Curacao"                 , "America/Curacao"                 )
    , America_Danmarkshavn          ( "America/Danmarkshavn"            , "America/Danmarkshavn"            )
    , America_Dawson                ( "America/Dawson"                  , "America/Dawson"                  )
    , America_Dawson_Creek          ( "America/Dawson_Creek"            , "America/Dawson Creek"            )
    , America_Denver                ( "America/Denver"                  , "America/Denver"                  )
    , America_Detroit               ( "America/Detroit"                 , "America/Detroit"                 )
    , America_Dominica              ( "America/Dominica"                , "America/Dominica"                )
    , America_Edmonton              ( "America/Edmonton"                , "America/Edmonton"                )
    , America_Eirunepe              ( "America/Eirunepe"                , "America/Eirunepe"                )
    , America_El_Salvador           ( "America/El_Salvador"             , "America/El Salvador"             )
    , America_Ensenada              ( "America/Ensenada"                , "America/Ensenada"                )
    , America_Fort_Wayne            ( "America/Fort_Wayne"              , "America/Fort Wayne"              )
    , America_Fortaleza             ( "America/Fortaleza"               , "America/Fortaleza"               )
    , America_Glace_Bay             ( "America/Glace_Bay"               , "America/Glace Bay"               )
    , America_Godthab               ( "America/Godthab"                 , "America/Godthab"                 )
    , America_Goose_Bay             ( "America/Goose_Bay"               , "America/Goose Bay"               )
    , America_Grand_Turk            ( "America/Grand_Turk"              , "America/Grand Turk"              )
    , America_Grenada               ( "America/Grenada"                 , "America/Grenada"                 )
    , America_Guadeloupe            ( "America/Guadeloupe"              , "America/Guadeloupe"              )
    , America_Guatemala             ( "America/Guatemala"               , "America/Guatemala"               )
    , America_Guayaquil             ( "America/Guayaquil"               , "America/Guayaquil"               )
    , America_Guyana                ( "America/Guyana"                  , "America/Guyana"                  )
    , America_Halifax               ( "America/Halifax"                 , "America/Halifax"                 )
    , America_Havana                ( "America/Havana"                  , "America/Havana"                  )
    , America_Hermosillo            ( "America/Hermosillo"              , "America/Hermosillo"              )
    , America_Indiana_Indianapolis  ( "America/Indiana/Indianapolis"    , "America/Indiana/Indianapolis"    )
    , America_Indiana_Knox          ( "America/Indiana/Knox"            , "America/Indiana/Knox"            )
    , America_Indiana_Marengo       ( "America/Indiana/Marengo"         , "America/Indiana/Marengo"         )
    , America_Indiana_Vevay         ( "America/Indiana/Vevay"           , "America/Indiana/Vevay"           )
    , America_Indianapolis          ( "America/Indianapolis"            , "America/Indianapolis"            )
    , America_Inuvik                ( "America/Inuvik"                  , "America/Inuvik"                  )
    , America_Iqaluit               ( "America/Iqaluit"                 , "America/Iqaluit"                 )
    , America_Jamaica               ( "America/Jamaica"                 , "America/Jamaica"                 )
    , America_Jujuy                 ( "America/Jujuy"                   , "America/Jujuy"                   )
    , America_Juneau                ( "America/Juneau"                  , "America/Juneau"                  )
    , America_Kentucky_Louisville   ( "America/Kentucky/Louisville"     , "America/Kentucky/Louisville"     )
    , America_Kentucky_Monticello   ( "America/Kentucky/Monticello"     , "America/Kentucky/Monticello"     )
    , America_Knox_IN               ( "America/Knox_IN"                 , "America/Knox IN"                 )
    , America_La_Paz                ( "America/La_Paz"                  , "America/La Paz"                  )
    , America_Lima                  ( "America/Lima"                    , "America/Lima"                    )
    , America_Los_Angeles           ( "America/Los_Angeles"             , "America/Los Angeles"             )
    , America_Louisville            ( "America/Louisville"              , "America/Louisville"              )
    , America_Maceio                ( "America/Maceio"                  , "America/Maceio"                  )
    , America_Managua               ( "America/Managua"                 , "America/Managua"                 )
    , America_Manaus                ( "America/Manaus"                  , "America/Manaus"                  )
    , America_Martinique            ( "America/Martinique"              , "America/Martinique"              )
    , America_Mazatlan              ( "America/Mazatlan"                , "America/Mazatlan"                )
    , America_Mendoza               ( "America/Mendoza"                 , "America/Mendoza"                 )
    , America_Menominee             ( "America/Menominee"               , "America/Menominee"               )
    , America_Merida                ( "America/Merida"                  , "America/Merida"                  )
    , America_Mexico_City           ( "America/Mexico_City"             , "America/Mexico City"             )
    , America_Miquelon              ( "America/Miquelon"                , "America/Miquelon"                )
    , America_Monterrey             ( "America/Monterrey"               , "America/Monterrey"               )
    , America_Montevideo            ( "America/Montevideo"              , "America/Montevideo"              )
    , America_Montreal              ( "America/Montreal"                , "America/Montreal"                )
    , America_Montserrat            ( "America/Montserrat"              , "America/Montserrat"              )
    , America_Nassau                ( "America/Nassau"                  , "America/Nassau"                  )
    , America_New_York              ( "America/New_York"                , "America/New York"                )
    , America_Nipigon               ( "America/Nipigon"                 , "America/Nipigon"                 )
    , America_Nome                  ( "America/Nome"                    , "America/Nome"                    )
    , America_Noronha               ( "America/Noronha"                 , "America/Noronha"                 )
    , America_North_Dakota_Center   ( "America/North_Dakota/Center"     , "America/North Dakota/Center"     )
    , America_Panama                ( "America/Panama"                  , "America/Panama"                  )
    , America_Pangnirtung           ( "America/Pangnirtung"             , "America/Pangnirtung"             )
    , America_Paramaribo            ( "America/Paramaribo"              , "America/Paramaribo"              )
    , America_Phoenix               ( "America/Phoenix"                 , "America/Phoenix"                 )
    , America_Port_of_Spain         ( "America/Port_of_Spain"           , "America/Port of Spain"           )
    , America_Port_au_Prince        ( "America/Port-au-Prince"          , "America/Port-au-Prince"          )
    , America_Porto_Acre            ( "America/Porto_Acre"              , "America/Porto Acre"              )
    , America_Porto_Velho           ( "America/Porto_Velho"             , "America/Porto Velho"             )
    , America_Puerto_Rico           ( "America/Puerto_Rico"             , "America/Puerto Rico"             )
    , America_Rainy_River           ( "America/Rainy_River"             , "America/Rainy River"             )
    , America_Rankin_Inlet          ( "America/Rankin_Inlet"            , "America/Rankin Inlet"            )
    , America_Recife                ( "America/Recife"                  , "America/Recife"                  )
    , America_Regina                ( "America/Regina"                  , "America/Regina"                  )
    , America_Rio_Branco            ( "America/Rio_Branco"              , "America/Rio Branco"              )
    , America_Rosario               ( "America/Rosario"                 , "America/Rosario"                 )
    , America_Santiago              ( "America/Santiago"                , "America/Santiago"                )
    , America_Santo_Domingo         ( "America/Santo_Domingo"           , "America/Santo Domingo"           )
    , America_Sao_Paulo             ( "America/Sao_Paulo"               , "America/Sao Paulo"               )
    , America_Scoresbysund          ( "America/Scoresbysund"            , "America/Scoresbysund"            )
    , America_Shiprock              ( "America/Shiprock"                , "America/Shiprock"                )
    , America_St_Johns              ( "America/St_Johns"                , "America/St Johns"                )
    , America_St_Kitts              ( "America/St_Kitts"                , "America/St Kitts"                )
    , America_St_Lucia              ( "America/St_Lucia"                , "America/St Lucia"                )
    , America_St_Thomas             ( "America/St_Thomas"               , "America/St Thomas"               )
    , America_St_Vincent            ( "America/St_Vincent"              , "America/St Vincent"              )
    , America_Swift_Current         ( "America/Swift_Current"           , "America/Swift Current"           )
    , America_Tegucigalpa           ( "America/Tegucigalpa"             , "America/Tegucigalpa"             )
    , America_Thule                 ( "America/Thule"                   , "America/Thule"                   )
    , America_Thunder_Bay           ( "America/Thunder_Bay"             , "America/Thunder Bay"             )
    , America_Tijuana               ( "America/Tijuana"                 , "America/Tijuana"                 )
    , America_Toronto               ( "America/Toronto"                 , "America/Toronto"                 )
    , America_Tortola               ( "America/Tortola"                 , "America/Tortola"                 )
    , America_Vancouver             ( "America/Vancouver"               , "America/Vancouver"               )
    , America_Virgin                ( "America/Virgin"                  , "America/Virgin"                  )
    , America_Whitehorse            ( "America/Whitehorse"              , "America/Whitehorse"              )
    , America_Winnipeg              ( "America/Winnipeg"                , "America/Winnipeg"                )
    , America_Yakutat               ( "America/Yakutat"                 , "America/Yakutat"                 )
    , America_Yellowknife           ( "America/Yellowknife"             , "America/Yellowknife"             )
    , Africa_Abidjan                ( "Africa/Abidjan"                  , "Africa/Abidjan"                  )
    , Africa_Accra                  ( "Africa/Accra"                    , "Africa/Accra"                    )
    , Africa_Addis_Ababa            ( "Africa/Addis_Ababa"              , "Africa/Addis Ababa"              )
    , Africa_Algiers                ( "Africa/Algiers"                  , "Africa/Algiers"                  )
    , Africa_Asmera                 ( "Africa/Asmera"                   , "Africa/Asmera"                   )
    , Africa_Bamako                 ( "Africa/Bamako"                   , "Africa/Bamako"                   )
    , Africa_Bangui                 ( "Africa/Bangui"                   , "Africa/Bangui"                   )
    , Africa_Banjul                 ( "Africa/Banjul"                   , "Africa/Banjul"                   )
    , Africa_Bissau                 ( "Africa/Bissau"                   , "Africa/Bissau"                   )
    , Africa_Blantyre               ( "Africa/Blantyre"                 , "Africa/Blantyre"                 )
    , Africa_Brazzaville            ( "Africa/Brazzaville"              , "Africa/Brazzaville"              )
    , Africa_Bujumbura              ( "Africa/Bujumbura"                , "Africa/Bujumbura"                )
    , Africa_Cairo                  ( "Africa/Cairo"                    , "Africa/Cairo"                    )
    , Africa_Casablanca             ( "Africa/Casablanca"               , "Africa/Casablanca"               )
    , Africa_Ceuta                  ( "Africa/Ceuta"                    , "Africa/Ceuta"                    )
    , Africa_Conakry                ( "Africa/Conakry"                  , "Africa/Conakry"                  )
    , Africa_Dakar                  ( "Africa/Dakar"                    , "Africa/Dakar"                    )
    , Africa_Dar_es_Salaam          ( "Africa/Dar_es_Salaam"            , "Africa/Dar es Salaam"            )
    , Africa_Djibouti               ( "Africa/Djibouti"                 , "Africa/Djibouti"                 )
    , Africa_Douala                 ( "Africa/Douala"                   , "Africa/Douala"                   )
    , Africa_El_Aaiun               ( "Africa/El_Aaiun"                 , "Africa/El Aaiun"                 )
    , Africa_Freetown               ( "Africa/Freetown"                 , "Africa/Freetown"                 )
    , Africa_Gaborone               ( "Africa/Gaborone"                 , "Africa/Gaborone"                 )
    , Africa_Harare                 ( "Africa/Harare"                   , "Africa/Harare"                   )
    , Africa_Johannesburg           ( "Africa/Johannesburg"             , "Africa/Johannesburg"             )
    , Africa_Kampala                ( "Africa/Kampala"                  , "Africa/Kampala"                  )
    , Africa_Khartoum               ( "Africa/Khartoum"                 , "Africa/Khartoum"                 )
    , Africa_Kigali                 ( "Africa/Kigali"                   , "Africa/Kigali"                   )
    , Africa_Kinshasa               ( "Africa/Kinshasa"                 , "Africa/Kinshasa"                 )
    , Africa_Lagos                  ( "Africa/Lagos"                    , "Africa/Lagos"                    )
    , Africa_Libreville             ( "Africa/Libreville"               , "Africa/Libreville"               )
    , Africa_Lome                   ( "Africa/Lome"                     , "Africa/Lome"                     )
    , Africa_Luanda                 ( "Africa/Luanda"                   , "Africa/Luanda"                   )
    , Africa_Lubumbashi             ( "Africa/Lubumbashi"               , "Africa/Lubumbashi"               )
    , Africa_Lusaka                 ( "Africa/Lusaka"                   , "Africa/Lusaka"                   )
    , Africa_Malabo                 ( "Africa/Malabo"                   , "Africa/Malabo"                   )
    , Africa_Maputo                 ( "Africa/Maputo"                   , "Africa/Maputo"                   )
    , Africa_Maseru                 ( "Africa/Maseru"                   , "Africa/Maseru"                   )
    , Africa_Mbabane                ( "Africa/Mbabane"                  , "Africa/Mbabane"                  )
    , Africa_Mogadishu              ( "Africa/Mogadishu"                , "Africa/Mogadishu"                )
    , Africa_Monrovia               ( "Africa/Monrovia"                 , "Africa/Monrovia"                 )
    , Africa_Nairobi                ( "Africa/Nairobi"                  , "Africa/Nairobi"                  )
    , Africa_Ndjamena               ( "Africa/Ndjamena"                 , "Africa/Ndjamena"                 )
    , Africa_Niamey                 ( "Africa/Niamey"                   , "Africa/Niamey"                   )
    , Africa_Nouakchott             ( "Africa/Nouakchott"               , "Africa/Nouakchott"               )
    , Africa_Ouagadougou            ( "Africa/Ouagadougou"              , "Africa/Ouagadougou"              )
    , Africa_Porto_Novo             ( "Africa/Porto-Novo"               , "Africa/Porto-Novo"               )
    , Africa_Sao_Tome               ( "Africa/Sao_Tome"                 , "Africa/Sao Tome"                 )
    , Africa_Timbuktu               ( "Africa/Timbuktu"                 , "Africa/Timbuktu"                 )
    , Africa_Tripoli                ( "Africa/Tripoli"                  , "Africa/Tripoli"                  )
    , Africa_Tunis                  ( "Africa/Tunis"                    , "Africa/Tunis"                    )
    , Africa_Windhoek               ( "Africa/Windhoek"                 , "Africa/Windhoek"                 )
    , Antarctica_Casey              ( "Antarctica/Casey"                , "Antarctica/Casey"                )
    , Antarctica_Davis              ( "Antarctica/Davis"                , "Antarctica/Davis"                )
    , Antarctica_DumontDUrville     ( "Antarctica/DumontDUrville"       , "Antarctica/DumontDUrville"       )
    , Antarctica_Mawson             ( "Antarctica/Mawson"               , "Antarctica/Mawson"               )
    , Antarctica_McMurdo            ( "Antarctica/McMurdo"              , "Antarctica/McMurdo"              )
    , Antarctica_Palmer             ( "Antarctica/Palmer"               , "Antarctica/Palmer"               )
    , Antarctica_Rothera            ( "Antarctica/Rothera"              , "Antarctica/Rothera"              )
    , Antarctica_South_Pole         ( "Antarctica/South_Pole"           , "Antarctica/South Pole"           )
    , Antarctica_Syowa              ( "Antarctica/Syowa"                , "Antarctica/Syowa"                )
    , Antarctica_Vostok             ( "Antarctica/Vostok"               , "Antarctica/Vostok"               )
    , Arctic_Longyearbyen           ( "Arctic/Longyearbyen"             , "Arctic/Longyearbyen"             )
    , Asia_Aden                     ( "Asia/Aden"                       , "Asia/Aden"                       )
    , Asia_Almaty                   ( "Asia/Almaty"                     , "Asia/Almaty"                     )
    , Asia_Amman                    ( "Asia/Amman"                      , "Asia/Amman"                      )
    , Asia_Anadyr                   ( "Asia/Anadyr"                     , "Asia/Anadyr"                     )
    , Asia_Aqtau                    ( "Asia/Aqtau"                      , "Asia/Aqtau"                      )
    , Asia_Aqtobe                   ( "Asia/Aqtobe"                     , "Asia/Aqtobe"                     )
    , Asia_Ashgabat                 ( "Asia/Ashgabat"                   , "Asia/Ashgabat"                   )
    , Asia_Ashkhabad                ( "Asia/Ashkhabad"                  , "Asia/Ashkhabad"                  )
    , Asia_Baghdad                  ( "Asia/Baghdad"                    , "Asia/Baghdad"                    )
    , Asia_Bahrain                  ( "Asia/Bahrain"                    , "Asia/Bahrain"                    )
    , Asia_Baku                     ( "Asia/Baku"                       , "Asia/Baku"                       )
    , Asia_Bangkok                  ( "Asia/Bangkok"                    , "Asia/Bangkok"                    )
    , Asia_Beirut                   ( "Asia/Beirut"                     , "Asia/Beirut"                     )
    , Asia_Bishkek                  ( "Asia/Bishkek"                    , "Asia/Bishkek"                    )
    , Asia_Brunei                   ( "Asia/Brunei"                     , "Asia/Brunei"                     )
    , Asia_Calcutta                 ( "Asia/Calcutta"                   , "Asia/Calcutta"                   )
    , Asia_Choibalsan               ( "Asia/Choibalsan"                 , "Asia/Choibalsan"                 )
    , Asia_Chongqing                ( "Asia/Chongqing"                  , "Asia/Chongqing"                  )
    , Asia_Chungking                ( "Asia/Chungking"                  , "Asia/Chungking"                  )
    , Asia_Colombo                  ( "Asia/Colombo"                    , "Asia/Colombo"                    )
    , Asia_Dacca                    ( "Asia/Dacca"                      , "Asia/Dacca"                      )
    , Asia_Damascus                 ( "Asia/Damascus"                   , "Asia/Damascus"                   )
    , Asia_Dhaka                    ( "Asia/Dhaka"                      , "Asia/Dhaka"                      )
    , Asia_Dili                     ( "Asia/Dili"                       , "Asia/Dili"                       )
    , Asia_Dubai                    ( "Asia/Dubai"                      , "Asia/Dubai"                      )
    , Asia_Dushanbe                 ( "Asia/Dushanbe"                   , "Asia/Dushanbe"                   )
    , Asia_Gaza                     ( "Asia/Gaza"                       , "Asia/Gaza"                       )
    , Asia_Harbin                   ( "Asia/Harbin"                     , "Asia/Harbin"                     )
    , Asia_Hong_Kong                ( "Asia/Hong_Kong"                  , "Asia/Hong Kong"                  )
    , Asia_Hovd                     ( "Asia/Hovd"                       , "Asia/Hovd"                       )
    , Asia_Irkutsk                  ( "Asia/Irkutsk"                    , "Asia/Irkutsk"                    )
    , Asia_Istanbul                 ( "Asia/Istanbul"                   , "Asia/Istanbul"                   )
    , Asia_Jakarta                  ( "Asia/Jakarta"                    , "Asia/Jakarta"                    )
    , Asia_Jayapura                 ( "Asia/Jayapura"                   , "Asia/Jayapura"                   )
    , Asia_Jerusalem                ( "Asia/Jerusalem"                  , "Asia/Jerusalem"                  )
    , Asia_Kabul                    ( "Asia/Kabul"                      , "Asia/Kabul"                      )
    , Asia_Kamchatka                ( "Asia/Kamchatka"                  , "Asia/Kamchatka"                  )
    , Asia_Karachi                  ( "Asia/Karachi"                    , "Asia/Karachi"                    )
    , Asia_Kashgar                  ( "Asia/Kashgar"                    , "Asia/Kashgar"                    )
    , Asia_Katmandu                 ( "Asia/Katmandu"                   , "Asia/Katmandu"                   )
    , Asia_Krasnoyarsk              ( "Asia/Krasnoyarsk"                , "Asia/Krasnoyarsk"                )
    , Asia_Kuala_Lumpur             ( "Asia/Kuala_Lumpur"               , "Asia/Kuala Lumpur"               )
    , Asia_Kuching                  ( "Asia/Kuching"                    , "Asia/Kuching"                    )
    , Asia_Kuwait                   ( "Asia/Kuwait"                     , "Asia/Kuwait"                     )
    , Asia_Macao                    ( "Asia/Macao"                      , "Asia/Macao"                      )
    , Asia_Macau                    ( "Asia/Macau"                      , "Asia/Macau"                      )
    , Asia_Magadan                  ( "Asia/Magadan"                    , "Asia/Magadan"                    )
    , Asia_Makassar                 ( "Asia/Makassar"                   , "Asia/Makassar"                   )
    , Asia_Manila                   ( "Asia/Manila"                     , "Asia/Manila"                     )
    , Asia_Muscat                   ( "Asia/Muscat"                     , "Asia/Muscat"                     )
    , Asia_Nicosia                  ( "Asia/Nicosia"                    , "Asia/Nicosia"                    )
    , Asia_Novosibirsk              ( "Asia/Novosibirsk"                , "Asia/Novosibirsk"                )
    , Asia_Omsk                     ( "Asia/Omsk"                       , "Asia/Omsk"                       )
    , Asia_Oral                     ( "Asia/Oral"                       , "Asia/Oral"                       )
    , Asia_Phnom_Penh               ( "Asia/Phnom_Penh"                 , "Asia/Phnom Penh"                 )
    , Asia_Pontianak                ( "Asia/Pontianak"                  , "Asia/Pontianak"                  )
    , Asia_Pyongyang                ( "Asia/Pyongyang"                  , "Asia/Pyongyang"                  )
    , Asia_Qatar                    ( "Asia/Qatar"                      , "Asia/Qatar"                      )
    , Asia_Qyzylorda                ( "Asia/Qyzylorda"                  , "Asia/Qyzylorda"                  )
    , Asia_Rangoon                  ( "Asia/Rangoon"                    , "Asia/Rangoon"                    )
    , Asia_Riyadh                   ( "Asia/Riyadh"                     , "Asia/Riyadh"                     )
    , Asia_Riyadh87                 ( "Asia/Riyadh87"                   , "Asia/Riyadh87"                   )
    , Asia_Riyadh88                 ( "Asia/Riyadh88"                   , "Asia/Riyadh88"                   )
    , Asia_Riyadh89                 ( "Asia/Riyadh89"                   , "Asia/Riyadh89"                   )
    , Asia_Saigon                   ( "Asia/Saigon"                     , "Asia/Saigon"                     )
    , Asia_Sakhalin                 ( "Asia/Sakhalin"                   , "Asia/Sakhalin"                   )
    , Asia_Samarkand                ( "Asia/Samarkand"                  , "Asia/Samarkand"                  )
    , Asia_Seoul                    ( "Asia/Seoul"                      , "Asia/Seoul"                      )
    , Asia_Shanghai                 ( "Asia/Shanghai"                   , "Asia/Shanghai"                   )
    , Asia_Singapore                ( "Asia/Singapore"                  , "Asia/Singapore"                  )
    , Asia_Taipei                   ( "Asia/Taipei"                     , "Asia/Taipei"                     )
    , Asia_Tashkent                 ( "Asia/Tashkent"                   , "Asia/Tashkent"                   )
    , Asia_Tbilisi                  ( "Asia/Tbilisi"                    , "Asia/Tbilisi"                    )
    , Asia_Tehran                   ( "Asia/Tehran"                     , "Asia/Tehran"                     )
    , Asia_Tel_Aviv                 ( "Asia/Tel_Aviv"                   , "Asia/Tel Aviv"                   )
    , Asia_Thimbu                   ( "Asia/Thimbu"                     , "Asia/Thimbu"                     )
    , Asia_Thimphu                  ( "Asia/Thimphu"                    , "Asia/Thimphu"                    )
    , Asia_Tokyo                    ( "Asia/Tokyo"                      , "Asia/Tokyo"                      )
    , Asia_Ujung_Pandang            ( "Asia/Ujung_Pandang"              , "Asia/Ujung Pandang"              )
    , Asia_Ulaanbaatar              ( "Asia/Ulaanbaatar"                , "Asia/Ulaanbaatar"                )
    , Asia_Ulan_Bator               ( "Asia/Ulan_Bator"                 , "Asia/Ulan Bator"                 )
    , Asia_Urumqi                   ( "Asia/Urumqi"                     , "Asia/Urumqi"                     )
    , Asia_Vientiane                ( "Asia/Vientiane"                  , "Asia/Vientiane"                  )
    , Asia_Vladivostok              ( "Asia/Vladivostok"                , "Asia/Vladivostok"                )
    , Asia_Yakutsk                  ( "Asia/Yakutsk"                    , "Asia/Yakutsk"                    )
    , Asia_Yekaterinburg            ( "Asia/Yekaterinburg"              , "Asia/Yekaterinburg"              )
    , Asia_Yerevan                  ( "Asia/Yerevan"                    , "Asia/Yerevan"                    )
    , Atlantic_Azores               ( "Atlantic/Azores"                 , "Atlantic/Azores"                 )
    , Atlantic_Bermuda              ( "Atlantic/Bermuda"                , "Atlantic/Bermuda"                )
    , Atlantic_Canary               ( "Atlantic/Canary"                 , "Atlantic/Canary"                 )
    , Atlantic_Cape_Verde           ( "Atlantic/Cape_Verde"             , "Atlantic/Cape Verde"             )
    , Atlantic_Faeroe               ( "Atlantic/Faeroe"                 , "Atlantic/Faeroe"                 )
    , Atlantic_Jan_Mayen            ( "Atlantic/Jan_Mayen"              , "Atlantic/Jan Mayen"              )
    , Atlantic_Madeira              ( "Atlantic/Madeira"                , "Atlantic/Madeira"                )
    , Atlantic_Reykjavik            ( "Atlantic/Reykjavik"              , "Atlantic/Reykjavik"              )
    , Atlantic_South_Georgia        ( "Atlantic/South_Georgia"          , "Atlantic/South Georgia"          )
    , Atlantic_St_Helena            ( "Atlantic/St_Helena"              , "Atlantic/St Helena"              )
    , Atlantic_Stanley              ( "Atlantic/Stanley"                , "Atlantic/Stanley"                )
    , Australia_ACT                 ( "Australia/ACT"                   , "Australia/ACT"                   )
    , Australia_Adelaide            ( "Australia/Adelaide"              , "Australia/Adelaide"              )
    , Australia_Brisbane            ( "Australia/Brisbane"              , "Australia/Brisbane"              )
    , Australia_Broken_Hill         ( "Australia/Broken_Hill"           , "Australia/Broken Hill"           )
    , Australia_Canberra            ( "Australia/Canberra"              , "Australia/Canberra"              )
    , Australia_Darwin              ( "Australia/Darwin"                , "Australia/Darwin"                )
    , Australia_Hobart              ( "Australia/Hobart"                , "Australia/Hobart"                )
    , Australia_LHI                 ( "Australia/LHI"                   , "Australia/LHI"                   )
    , Australia_Lindeman            ( "Australia/Lindeman"              , "Australia/Lindeman"              )
    , Australia_Lord_Howe           ( "Australia/Lord_Howe"             , "Australia/Lord Howe"             )
    , Australia_Melbourne           ( "Australia/Melbourne"             , "Australia/Melbourne"             )
    , Australia_North               ( "Australia/North"                 , "Australia/North"                 )
    , Australia_NSW                 ( "Australia/NSW"                   , "Australia/NSW"                   )
    , Australia_Perth               ( "Australia/Perth"                 , "Australia/Perth"                 )
    , Australia_Queensland          ( "Australia/Queensland"            , "Australia/Queensland"            )
    , Australia_South               ( "Australia/South"                 , "Australia/South"                 )
    , Australia_Sydney              ( "Australia/Sydney"                , "Australia/Sydney"                )
    , Australia_Tasmania            ( "Australia/Tasmania"              , "Australia/Tasmania"              )
    , Australia_Victoria            ( "Australia/Victoria"              , "Australia/Victoria"              )
    , Australia_West                ( "Australia/West"                  , "Australia/West"                  )
    , Australia_Yancowinna          ( "Australia/Yancowinna"            , "Australia/Yancowinna"            )
    , Brazil_Acre                   ( "Brazil/Acre"                     , "Brazil/Acre"                     )
    , Brazil_DeNoronha              ( "Brazil/DeNoronha"                , "Brazil/DeNoronha"                )
    , Brazil_East                   ( "Brazil/East"                     , "Brazil/East"                     )
    , Brazil_West                   ( "Brazil/West"                     , "Brazil/West"                     )
    , Canada_Atlantic               ( "Canada/Atlantic"                 , "Canada/Atlantic"                 )
    , Canada_Central                ( "Canada/Central"                  , "Canada/Central"                  )
    , Canada_Eastern                ( "Canada/Eastern"                  , "Canada/Eastern"                  )
    , Canada_East_Saskatchewan      ( "Canada/East-Saskatchewan"        , "Canada/East-Saskatchewan"        )
    , Canada_Mountain               ( "Canada/Mountain"                 , "Canada/Mountain"                 )
    , Canada_Newfoundland           ( "Canada/Newfoundland"             , "Canada/Newfoundland"             )
    , Canada_Pacific                ( "Canada/Pacific"                  , "Canada/Pacific"                  )
    , Canada_Saskatchewan           ( "Canada/Saskatchewan"             , "Canada/Saskatchewan"             )
    , Canada_Yukon                  ( "Canada/Yukon"                    , "Canada/Yukon"                    )
    , Chile_Continental             ( "Chile/Continental"               , "Chile/Continental"               )
    , Chile_EasterIsland            ( "Chile/EasterIsland"              , "Chile/EasterIsland"              )
    , Egypt                         ( "Egypt"                           , "Egypt"                           )
    , Eire                          ( "Eire"                            , "Eire"                            )
    , Etc_GMT_Plus_1                ( "Etc/GMT+1"                       , "Etc/GMT+1"                       )
    , Etc_GMT_Plus_2                ( "Etc/GMT+2"                       , "Etc/GMT+2"                       )
    , Etc_GMT_Plus_3                ( "Etc/GMT+3"                       , "Etc/GMT+3"                       )
    , Etc_GMT_Plus_4                ( "Etc/GMT+4"                       , "Etc/GMT+4"                       )
    , Etc_GMT_Plus_5                ( "Etc/GMT+5"                       , "Etc/GMT+5"                       )
    , Etc_GMT_Plus_6                ( "Etc/GMT+6"                       , "Etc/GMT+6"                       )
    , Etc_GMT_Plus_7                ( "Etc/GMT+7"                       , "Etc/GMT+7"                       )
    , Etc_GMT_Plus_8                ( "Etc/GMT+8"                       , "Etc/GMT+8"                       )
    , Etc_GMT_Plus_9                ( "Etc/GMT+9"                       , "Etc/GMT+9"                       )
    , Etc_GMT_Plus_10               ( "Etc/GMT+10"                      , "Etc/GMT+10"                      )
    , Etc_GMT_Plus_11               ( "Etc/GMT+11"                      , "Etc/GMT+11"                      )
    , Etc_GMT_Plus_12               ( "Etc/GMT+12"                      , "Etc/GMT+12"                      )
    , UTC                           ( "UTC"                             , "UTC"                             )
    , Etc_GMT_Minus_1               ( "Etc/GMT-1"                       , "Etc/GMT-1"                       )
    , Etc_GMT_Minus_2               ( "Etc/GMT-2"                       , "Etc/GMT-2"                       )
    , Etc_GMT_Minus_3               ( "Etc/GMT-3"                       , "Etc/GMT-3"                       )
    , Etc_GMT_Minus_4               ( "Etc/GMT-4"                       , "Etc/GMT-4"                       )
    , Etc_GMT_Minus_5               ( "Etc/GMT-5"                       , "Etc/GMT-5"                       )
    , Etc_GMT_Minus_6               ( "Etc/GMT-6"                       , "Etc/GMT-6"                       )
    , Etc_GMT_Minus_7               ( "Etc/GMT-7"                       , "Etc/GMT-7"                       )
    , Etc_GMT_Minus_8               ( "Etc/GMT-8"                       , "Etc/GMT-8"                       )
    , Etc_GMT_Minus_9               ( "Etc/GMT-9"                       , "Etc/GMT-9"                       )
    , Etc_GMT_Minus_10              ( "Etc/GMT-10"                      , "Etc/GMT-10"                      )
    , Etc_GMT_Minus_11              ( "Etc/GMT-11"                      , "Etc/GMT-11"                      )
    , Etc_GMT_Minus_12              ( "Etc/GMT-12"                      , "Etc/GMT-12"                      )
    , Etc_GMT_Minus_13              ( "Etc/GMT-13"                      , "Etc/GMT-13"                      )
    , Etc_GMT_Minus_14              ( "Etc/GMT-14"                      , "Etc/GMT-14"                      )
    , Europe_Amsterdam              ( "Europe/Amsterdam"                , "Europe/Amsterdam"                )
    , Europe_Andorra                ( "Europe/Andorra"                  , "Europe/Andorra"                  )
    , Europe_Athens                 ( "Europe/Athens"                   , "Europe/Athens"                   )
    , Europe_Belfast                ( "Europe/Belfast"                  , "Europe/Belfast"                  )
    , Europe_Belgrade               ( "Europe/Belgrade"                 , "Europe/Belgrade"                 )
    , Europe_Berlin                 ( "Europe/Berlin"                   , "Europe/Berlin"                   )
    , Europe_Bratislava             ( "Europe/Bratislava"               , "Europe/Bratislava"               )
    , Europe_Brussels               ( "Europe/Brussels"                 , "Europe/Brussels"                 )
    , Europe_Bucharest              ( "Europe/Bucharest"                , "Europe/Bucharest"                )
    , Europe_Budapest               ( "Europe/Budapest"                 , "Europe/Budapest"                 )
    , Europe_Chisinau               ( "Europe/Chisinau"                 , "Europe/Chisinau"                 )
    , Europe_Copenhagen             ( "Europe/Copenhagen"               , "Europe/Copenhagen"               )
    , Europe_Dublin                 ( "Europe/Dublin"                   , "Europe/Dublin"                   )
    , Europe_Gibraltar              ( "Europe/Gibraltar"                , "Europe/Gibraltar"                )
    , Europe_Helsinki               ( "Europe/Helsinki"                 , "Europe/Helsinki"                 )
    , Europe_Istanbul               ( "Europe/Istanbul"                 , "Europe/Istanbul"                 )
    , Europe_Kaliningrad            ( "Europe/Kaliningrad"              , "Europe/Kaliningrad"              )
    , Europe_Kiev                   ( "Europe/Kiev"                     , "Europe/Kiev"                     )
    , Europe_Lisbon                 ( "Europe/Lisbon"                   , "Europe/Lisbon"                   )
    , Europe_Ljubljana              ( "Europe/Ljubljana"                , "Europe/Ljubljana"                )
    , Europe_London                 ( "Europe/London"                   , "Europe/London"                   )
    , Europe_Luxembourg             ( "Europe/Luxembourg"               , "Europe/Luxembourg"               )
    , Europe_Madrid                 ( "Europe/Madrid"                   , "Europe/Madrid"                   )
    , Europe_Malta                  ( "Europe/Malta"                    , "Europe/Malta"                    )
    , Europe_Minsk                  ( "Europe/Minsk"                    , "Europe/Minsk"                    )
    , Europe_Monaco                 ( "Europe/Monaco"                   , "Europe/Monaco"                   )
    , Europe_Moscow                 ( "Europe/Moscow"                   , "Europe/Moscow"                   )
    , Europe_Nicosia                ( "Europe/Nicosia"                  , "Europe/Nicosia"                  )
    , Europe_Oslo                   ( "Europe/Oslo"                     , "Europe/Oslo"                     )
    , Europe_Paris                  ( "Europe/Paris"                    , "Europe/Paris"                    )
    , Europe_Prague                 ( "Europe/Prague"                   , "Europe/Prague"                   )
    , Europe_Riga                   ( "Europe/Riga"                     , "Europe/Riga"                     )
    , Europe_Rome                   ( "Europe/Rome"                     , "Europe/Rome"                     )
    , Europe_Samara                 ( "Europe/Samara"                   , "Europe/Samara"                   )
    , Europe_San_Marino             ( "Europe/San_Marino"               , "Europe/San Marino"               )
    , Europe_Sarajevo               ( "Europe/Sarajevo"                 , "Europe/Sarajevo"                 )
    , Europe_Simferopol             ( "Europe/Simferopol"               , "Europe/Simferopol"               )
    , Europe_Skopje                 ( "Europe/Skopje"                   , "Europe/Skopje"                   )
    , Europe_Sofia                  ( "Europe/Sofia"                    , "Europe/Sofia"                    )
    , Europe_Stockholm              ( "Europe/Stockholm"                , "Europe/Stockholm"                )
    , Europe_Tallinn                ( "Europe/Tallinn"                  , "Europe/Tallinn"                  )
    , Europe_Tirane                 ( "Europe/Tirane"                   , "Europe/Tirane"                   )
    , Europe_Tiraspol               ( "Europe/Tiraspol"                 , "Europe/Tiraspol"                 )
    , Europe_Uzhgorod               ( "Europe/Uzhgorod"                 , "Europe/Uzhgorod"                 )
    , Europe_Vaduz                  ( "Europe/Vaduz"                    , "Europe/Vaduz"                    )
    , Europe_Vatican                ( "Europe/Vatican"                  , "Europe/Vatican"                  )
    , Europe_Vienna                 ( "Europe/Vienna"                   , "Europe/Vienna"                   )
    , Europe_Vilnius                ( "Europe/Vilnius"                  , "Europe/Vilnius"                  )
    , Europe_Warsaw                 ( "Europe/Warsaw"                   , "Europe/Warsaw"                   )
    , Europe_Zagreb                 ( "Europe/Zagreb"                   , "Europe/Zagreb"                   )
    , Europe_Zaporozhye             ( "Europe/Zaporozhye"               , "Europe/Zaporozhye"               )
    , Europe_Zurich                 ( "Europe/Zurich"                   , "Europe/Zurich"                   )
    , Hongkong                      ( "Hongkong"                        , "Hongkong"                        )
    , Iceland                       ( "Iceland"                         , "Iceland"                         )
    , Indian_Antananarivo           ( "Indian/Antananarivo"             , "Indian/Antananarivo"             )
    , Indian_Chagos                 ( "Indian/Chagos"                   , "Indian/Chagos"                   )
    , Indian_Christmas              ( "Indian/Christmas"                , "Indian/Christmas"                )
    , Indian_Cocos                  ( "Indian/Cocos"                    , "Indian/Cocos"                    )
    , Indian_Comoro                 ( "Indian/Comoro"                   , "Indian/Comoro"                   )
    , Indian_Kerguelen              ( "Indian/Kerguelen"                , "Indian/Kerguelen"                )
    , Indian_Mahe                   ( "Indian/Mahe"                     , "Indian/Mahe"                     )
    , Indian_Maldives               ( "Indian/Maldives"                 , "Indian/Maldives"                 )
    , Indian_Mauritius              ( "Indian/Mauritius"                , "Indian/Mauritius"                )
    , Indian_Mayotte                ( "Indian/Mayotte"                  , "Indian/Mayotte"                  )
    , Indian_Reunion                ( "Indian/Reunion"                  , "Indian/Reunion"                  )
    , Iran                          ( "Iran"                            , "Iran"                            )
    , Israel                        ( "Israel"                          , "Israel"                          )
    , Jamaica                       ( "Jamaica"                         , "Jamaica"                         )
    , Japan                         ( "Japan"                           , "Japan"                           )
    , Kwajalein                     ( "Kwajalein"                       , "Kwajalein"                       )
    , Libya                         ( "Libya"                           , "Libya"                           )
    , Mexico_BajaNorte              ( "Mexico/BajaNorte"                , "Mexico/BajaNorte"                )
    , Mexico_BajaSur                ( "Mexico/BajaSur"                  , "Mexico/BajaSur"                  )
    , Mexico_General                ( "Mexico/General"                  , "Mexico/General"                  )
    , Mideast_Riyadh87              ( "Mideast/Riyadh87"                , "Mideast/Riyadh87"                )
    , Mideast_Riyadh88              ( "Mideast/Riyadh88"                , "Mideast/Riyadh88"                )
    , Mideast_Riyadh89              ( "Mideast/Riyadh89"                , "Mideast/Riyadh89"                )
    , Pacific_Apia                  ( "Pacific/Apia"                    , "Pacific/Apia"                    )
    , Pacific_Auckland              ( "Pacific/Auckland"                , "Pacific/Auckland"                )
    , Pacific_Chatham               ( "Pacific/Chatham"                 , "Pacific/Chatham"                 )
    , Pacific_Easter                ( "Pacific/Easter"                  , "Pacific/Easter"                  )
    , Pacific_Efate                 ( "Pacific/Efate"                   , "Pacific/Efate"                   )
    , Pacific_Enderbury             ( "Pacific/Enderbury"               , "Pacific/Enderbury"               )
    , Pacific_Fakaofo               ( "Pacific/Fakaofo"                 , "Pacific/Fakaofo"                 )
    , Pacific_Fiji                  ( "Pacific/Fiji"                    , "Pacific/Fiji"                    )
    , Pacific_Funafuti              ( "Pacific/Funafuti"                , "Pacific/Funafuti"                )
    , Pacific_Galapagos             ( "Pacific/Galapagos"               , "Pacific/Galapagos"               )
    , Pacific_Gambier               ( "Pacific/Gambier"                 , "Pacific/Gambier"                 )
    , Pacific_Guadalcanal           ( "Pacific/Guadalcanal"             , "Pacific/Guadalcanal"             )
    , Pacific_Guam                  ( "Pacific/Guam"                    , "Pacific/Guam"                    )
    , Pacific_Honolulu              ( "Pacific/Honolulu"                , "Pacific/Honolulu"                )
    , Pacific_Johnston              ( "Pacific/Johnston"                , "Pacific/Johnston"                )
    , Pacific_Kiritimati            ( "Pacific/Kiritimati"              , "Pacific/Kiritimati"              )
    , Pacific_Kosrae                ( "Pacific/Kosrae"                  , "Pacific/Kosrae"                  )
    , Pacific_Kwajalein             ( "Pacific/Kwajalein"               , "Pacific/Kwajalein"               )
    , Pacific_Majuro                ( "Pacific/Majuro"                  , "Pacific/Majuro"                  )
    , Pacific_Marquesas             ( "Pacific/Marquesas"               , "Pacific/Marquesas"               )
    , Pacific_Midway                ( "Pacific/Midway"                  , "Pacific/Midway"                  )
    , Pacific_Nauru                 ( "Pacific/Nauru"                   , "Pacific/Nauru"                   )
    , Pacific_Niue                  ( "Pacific/Niue"                    , "Pacific/Niue"                    )
    , Pacific_Norfolk               ( "Pacific/Norfolk"                 , "Pacific/Norfolk"                 )
    , Pacific_Noumea                ( "Pacific/Noumea"                  , "Pacific/Noumea"                  )
    , Pacific_Pago_Pago             ( "Pacific/Pago_Pago"               , "Pacific/Pago Pago"               )
    , Pacific_Palau                 ( "Pacific/Palau"                   , "Pacific/Palau"                   )
    , Pacific_Pitcairn              ( "Pacific/Pitcairn"                , "Pacific/Pitcairn"                )
    , Pacific_Ponape                ( "Pacific/Ponape"                  , "Pacific/Ponape"                  )
    , Pacific_Port_Moresby          ( "Pacific/Port_Moresby"            , "Pacific/Port Moresby"            )
    , Pacific_Rarotonga             ( "Pacific/Rarotonga"               , "Pacific/Rarotonga"               )
    , Pacific_Saipan                ( "Pacific/Saipan"                  , "Pacific/Saipan"                  )
    , Pacific_Samoa                 ( "Pacific/Samoa"                   , "Pacific/Samoa"                   )
    , Pacific_Tahiti                ( "Pacific/Tahiti"                  , "Pacific/Tahiti"                  )
    , Pacific_Tarawa                ( "Pacific/Tarawa"                  , "Pacific/Tarawa"                  )
    , Pacific_Tongatapu             ( "Pacific/Tongatapu"               , "Pacific/Tongatapu"               )
    , Pacific_Truk                  ( "Pacific/Truk"                    , "Pacific/Truk"                    )
    , Pacific_Wake                  ( "Pacific/Wake"                    , "Pacific/Wake"                    )
    , Pacific_Wallis                ( "Pacific/Wallis"                  , "Pacific/Wallis"                  )
    , Pacific_Yap                   ( "Pacific/Yap"                     , "Pacific/Yap"                     )
    , Poland                        ( "Poland"                          , "Poland"                          )
    , Portugal                      ( "Portugal"                        , "Portugal"                        )
    , Singapore                     ( "Singapore"                       , "Singapore"                       )
    ; 
    private static String[]                     displayValues;
    private static HashMap<String , TimeZoneId> map;
      
    static
    {
        map = new HashMap<>();
        
        for( TimeZoneId x : TimeZoneId.values() )
        {
            map.put( x.toString() , x );
        }
    }

    public static String[] displayValues(
    )
    {
        int                             indx = 0;

        if( displayValues == null )
        {
            displayValues = new String[ map.keySet().size() ];
            
            for( TimeZoneId stat : map.values() )
            {
                displayValues[ indx ] = stat.display();
                indx++;
            }
        }
        
        return displayValues;
    }
    
    public static TimeZoneId locate(
      String                        reqType
    )
    {
        return map.get( reqType );
    }
    

    //  ~ Instance fields ******************************************************
    private String                      display;
    private String                      value;

    
    //  ~ Constructor **********************************************************
    TimeZoneId(
      String                            value
    , String                            display
    )
    {
        this.value      = value;
        this.display    = display;
    }

    
    //  ~ Methods **************************************************************
    public String display(
    )
    {
        return display;
    }

    public void set(
      String                            value
    )
    {
        this.value = value;
    }

    @Override
    public String toString(
    )
    {
        return value;
    }

    public String value(
    )
    {
        return value;
    }

    public DateTimeZone toDateTimeZone(
    )
    {
        return DateTimeZone.forID( value );
    }
}
