--
-- This file was generated on 11/07/2015 at 02:56:03 PM.
-- It contains HsqlDb version 1.8.0.8 compatible SQL statements.
--

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'USER_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'RELEASE_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'TEAM_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'MILESTONE_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'IDEA_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'ROM_SIZE_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'STATUS_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'PHASE_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'USER_PREFS_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'COMMENT_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'AUTH_USER_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'TEAM_IMPACT_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'PHASE_APRVL_TYPE_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'PHASE_CMPLT_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'WORKFLOW_KEY', 100);

INSERT INTO RT_UNIQUE_KEY( KEY_NAME, LAST_USED_KEY_PREFIX) VALUES( 'STATUS_CMPLT_KEY', 100);


COMMIT WORK;