--
-- This file was generated on 11/07/2015 at 02:56:03 PM.
-- It contains HsqlDb version 1.8.0.8 compatible SQL statements.
--

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 1, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 2, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 3, 4);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 4, 5);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 6);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 7);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 8);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 1, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 2, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 3, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 4, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 10);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 1, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 2, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 3, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 4, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 9);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 2, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 3, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 4, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 1);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 4);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 5);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 6);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 7);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 9, 8);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 3, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 4, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 4, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 4);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 5, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 5);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 4);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 6, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 6);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 5);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 4);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 7, 2);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 7);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 6);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 5);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 4);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 3);

INSERT INTO RT_WORKFLOW_PHASE_NEXT_PHASE( PHASE_ID, NEXT_PHASE_ID) VALUES( 8, 2);


COMMIT WORK;